// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth.vue')['default']
    Dark: typeof import('./src/components/Dark.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GetStarted: typeof import('./src/components/GetStarted.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Ico: typeof import('./src/components/Ico.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}
