service: function
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  api:
    handler: app.handler
    url: true

plugins:
  - serverless-python-requirements
  - serverless-offline
